# Docker Stack configuration for internal PostgreSQL and S3 services
# This file should be used in addition to docker-stack.yml when using internal services
# Deploy with: docker stack deploy -c docker-stack.yml -c docker-stack-internal.yml openbalena
version: '3.8'

services:
  # Internal PostgreSQL database - only include when EXTERNAL_POSTGRES != true
  db:
    image: balena/open-balena-db:6.0.0
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      DB_NAME: resin
      DB_PASSWORD: docker
      DB_USER: docker
      LOG_LEVEL: DEBUG
      PRODUCTION_MODE: 'true'
    healthcheck:
      test: pg_isready -U "$${DB_USER}" -d "$${DB_NAME}"
      interval: 45s
      timeout: 15s
      retries: 3
    deploy:
      restart_policy:
        condition: any
    networks:
      - default

  # Internal S3 service - only include when EXTERNAL_S3 != true
  s3:
    image: balena/open-balena-s3:2.28.75
    volumes:
      - s3-data:/export
      - certs-data:/certs
      - resin-data:/balena
    environment:
      BUCKETS: registry-data;web-resources
      HOSTS_CONFIG: REGISTRY2_S3_REGION_ENDPOINT:s3,WEBRESOURCES_S3_HOST:s3
      TOKENS_CONFIG: REGISTRY2_S3_KEY:hex,REGISTRY2_S3_SECRET:hex,S3_MINIO_ACCESS_KEY:REGISTRY2_S3_KEY,S3_MINIO_SECRET_KEY:REGISTRY2_S3_SECRET,WEBRESOURCES_S3_ACCESS_KEY:REGISTRY2_S3_KEY,WEBRESOURCES_S3_SECRET_KEY:REGISTRY2_S3_SECRET
    healthcheck:
      test: /usr/src/app/docker-hc
      interval: 45s
      timeout: 15s
      retries: 3
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    security_opt:
      - apparmor=unconfined
    tmpfs:
      - /run
      - /sys/fs/cgroup
    deploy:
      restart_policy:
        condition: any
    networks:
      - default

volumes:
  cert-manager-data:
    external: true
  certs-data:
    external: true
  db-data:
    external: true
  pki-data:
    external: true
  redis-data:
    external: true
  resin-data:
    external: true
  s3-data:
    external: true
  builder-storage:
    external: true
  delta-storage:
    external: true
  helper-storage:
    external: true

networks:
  default:
    external: true
    name: openbalena_default